# Generated by Django 5.2.4 on 2025-08-02 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, help_text='Link to your location on a map (e.g. Google Maps).', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='registration_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Registration number must be like ABC-123.', regex='^[A-Z]{2,3}-\\d{1,3}$')]),
        ),
    ]
