# Generated by Django 5.2.4 on 2025-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_contactinfo_map_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, help_text='Paste the src URL from a Google Maps embed here.', null=True),
        ),
    ]
