# Generated by Django 5.2.4 on 2025-08-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_contactinfo_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, help_text='Paste a map share link here (e.g. https://goo.gl/maps/...).', null=True),
        ),
    ]
