# Generated by Django 5.2.4 on 2025-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_contactinfo_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Optional: paste a full <iframe> embed code here to display a map directly.', null=True),
        ),
    ]
